apiVersion: v1
kind: Pod
metadata:
  name: http-test-app
  labels:
    app: http-test-app
spec:
  containers:
  - name: http-test-app
    image: ghcr.io/vladkanatov/http-test-application:latest
    ports:
    - containerPort: 8080
      name: http
    env:
    - name: PORT
      value: "8080"
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
  restartPolicy: Always
