name: Build and Push Docker image with Kaniko

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker config
        run: |
          mkdir -p $HOME/.docker
          echo "{}" > $HOME/.docker/config.json

      - name: Build and push with Kaniko
        uses: aevea/action-kaniko@v0.11.0
        with:
          registry: ghcr.io
          image: vladkanatov/http-test-application
          tag: ${{ github.sha }}
          username: vladkanatov
          password: ${{ secrets.GITHUB_TOKEN }}
          build_file: ./Dockerfile
