name: Build and Push Docker image with Kaniko

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker config
        run: |
          mkdir -p $HOME/.docker
          echo "{}" > $HOME/.docker/config.json

      - name: Get short SHA
        id: vars
        run: echo "short_sha=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT

      - name: Build and push with Kaniko
        uses: aevea/action-kaniko@v0.14.0
        with:
          registry: ghcr.io/vladkanatov
          image: http-test-application
          tag: ${{ steps.vars.outputs.short_sha }}
          username: vladkanatov
          password: ${{ secrets.GITHUB_TOKEN }}
          build_file: ./Dockerfile
          cache: true
          cache_registry: ghcr.io/vladkanatov
          cache_ttl: 24h
          extra_args: --destination ghcr.io/vladkanatov/http-test-application:latest --destination ghcr.io/vladkanatov/http-test-application:cache
